packages:
  - "packages/_probe/*"
  - "packages/*"
  - "pipeline/*"
  - "core/*"
  - "brands/*/inputs/*"
  - "brands/*/inputs/*/*"
  - "brands/*/outputs/*"
  - "brands/*/outputs/*/*"
  - "brands/*/generated/*/*"
  - "brands/*/generated/*/*/*"
  - "!**/node_modules"
  - "!**/elm-stuff"
  - "!core/*/elm-html-intermediate-representation"

allowBuilds:
  '@parcel/watcher': true
  elm: true
  elm-format: true
  esbuild: true
  lamdera: true

minimumReleaseAgeExclude:
  - '@m3e/web@2.5.13'
