packages:
  - "packages/*"
  - "packages/*/*"
  - "!**/node_modules"
  - "!**/elm-stuff"
  - "!packages/*/elm-html-intermediate-representation"

allowBuilds:
  '@parcel/watcher': true
  elm: true
  elm-format: true
  esbuild: true
  lamdera: true

minimumReleaseAgeExclude:
  - '@m3e/web@2.5.13'
