// AUTO-GENERATED by src/tokens/stamp.mjs from profiles/m3-kit/tokens.json — DO NOT EDIT BY HAND.
// Regenerate: node src/tokens/stamp.mjs --profile m3-kit --out profiles/m3-kit/stamp/
//
// Corner — stamps 10 Figma variable(s)' codeSyntax.WEB
// with the canonical --md-sys-* custom property (evidence #6, the proven
// Tailwind-leg mechanism: get_design_context then emits var(--md-sys-*,<fallback>)
// in generated layout code for every stamped role).
//
// PORTABLE BY NAME (evidence #5): locates each variable via
// figma.variables.getLocalVariablesAsync() + a name match — never a baked-in
// variable id, which re-mints across file copies. Run this SAME script
// unmodified against the canonical copy, a throwaway Copy, or ADS.
//
// IDEMPOTENT: a variable whose codeSyntax.WEB already equals the intended
// value is skipped, not re-stamped.
//
// ⚑ HUMAN: applying this script to a real file is a per-file authorization —
// see profiles/m3-kit/stamp/README.md before running this via use_figma.

const TARGETS = [
  {
    "name": "Corner/Extra-extra-large",
    "value": "var(--md-sys-shape-corner-extra-extra-large)"
  },
  {
    "name": "Corner/Extra-large",
    "value": "var(--md-sys-shape-corner-extra-large)"
  },
  {
    "name": "Corner/Extra-large-increased",
    "value": "var(--md-sys-shape-corner-extra-large-increased)"
  },
  {
    "name": "Corner/Extra-small",
    "value": "var(--md-sys-shape-corner-extra-small)"
  },
  {
    "name": "Corner/Full",
    "value": "var(--md-sys-shape-corner-full)"
  },
  {
    "name": "Corner/Large",
    "value": "var(--md-sys-shape-corner-large)"
  },
  {
    "name": "Corner/Large-increased",
    "value": "var(--md-sys-shape-corner-large-increased)"
  },
  {
    "name": "Corner/Medium",
    "value": "var(--md-sys-shape-corner-medium)"
  },
  {
    "name": "Corner/None",
    "value": "var(--md-sys-shape-corner-none)"
  },
  {
    "name": "Corner/Small",
    "value": "var(--md-sys-shape-corner-small)"
  }
];

const byName = new Map();
for (const v of await figma.variables.getLocalVariablesAsync()) {
  byName.set(v.name, v);
}

const stamped = [];
const skipped = [];
const missing = [];
const mutatedVariableIds = [];

for (const target of TARGETS) {
  const v = byName.get(target.name);
  if (!v) {
    missing.push(target.name);
    continue;
  }
  const current = v.codeSyntax ? v.codeSyntax["WEB"] : undefined;
  if (current === target.value) {
    skipped.push(target.name);
    continue;
  }
  v.setVariableCodeSyntax("WEB", target.value);
  stamped.push(target.name);
  mutatedVariableIds.push(v.id);
}

return { stamped, skipped, missing, mutatedVariableIds };
