// AUTO-GENERATED by src/tokens/stamp.mjs from profiles/m3-kit/tokens.json — DO NOT EDIT BY HAND.
// Regenerate: node src/tokens/stamp.mjs --profile m3-kit --out profiles/m3-kit/stamp/
//
// INVERSE of stamp/01-schemes.js.
// Schemes (chunk 1/2) — restores 40 Figma variable(s)' codeSyntax.WEB
// to "{}" (removeVariableCodeSyntax). The checked-in token-table dump measures
// 0/304 variables with any codeSyntax today (evidence #13) — for this table,
// "restore to {}" and "restore to the recorded pre-state" are the same
// operation. If a target file's PRE-stamp state was ever non-empty, restore
// from the 00-snapshot.json captured before stamping instead (see README.md).
//
// PORTABLE BY NAME, IDEMPOTENT: same discipline as the stamp script — locates
// by name, and skips a variable whose codeSyntax.WEB does not currently equal
// the value we would have stamped (already restored, or never ours to touch).

const TARGETS = [
  {
    "name": "Schemes/Background",
    "value": "var(--md-sys-color-background)"
  },
  {
    "name": "Schemes/Error",
    "value": "var(--md-sys-color-error)"
  },
  {
    "name": "Schemes/Error Container",
    "value": "var(--md-sys-color-error-container)"
  },
  {
    "name": "Schemes/Inverse On Surface",
    "value": "var(--md-sys-color-inverse-on-surface)"
  },
  {
    "name": "Schemes/Inverse Primary",
    "value": "var(--md-sys-color-inverse-primary)"
  },
  {
    "name": "Schemes/Inverse Surface",
    "value": "var(--md-sys-color-inverse-surface)"
  },
  {
    "name": "Schemes/On Background",
    "value": "var(--md-sys-color-on-background)"
  },
  {
    "name": "Schemes/On Error",
    "value": "var(--md-sys-color-on-error)"
  },
  {
    "name": "Schemes/On Error Container",
    "value": "var(--md-sys-color-on-error-container)"
  },
  {
    "name": "Schemes/On Primary",
    "value": "var(--md-sys-color-on-primary)"
  },
  {
    "name": "Schemes/On Primary Container",
    "value": "var(--md-sys-color-on-primary-container)"
  },
  {
    "name": "Schemes/On Primary Fixed",
    "value": "var(--md-sys-color-on-primary-fixed)"
  },
  {
    "name": "Schemes/On Primary Fixed Variant",
    "value": "var(--md-sys-color-on-primary-fixed-variant)"
  },
  {
    "name": "Schemes/On Secondary",
    "value": "var(--md-sys-color-on-secondary)"
  },
  {
    "name": "Schemes/On Secondary Container",
    "value": "var(--md-sys-color-on-secondary-container)"
  },
  {
    "name": "Schemes/On Secondary Fixed",
    "value": "var(--md-sys-color-on-secondary-fixed)"
  },
  {
    "name": "Schemes/On Secondary Fixed Variant",
    "value": "var(--md-sys-color-on-secondary-fixed-variant)"
  },
  {
    "name": "Schemes/On Surface",
    "value": "var(--md-sys-color-on-surface)"
  },
  {
    "name": "Schemes/On Surface Variant",
    "value": "var(--md-sys-color-on-surface-variant)"
  },
  {
    "name": "Schemes/On Tertiary",
    "value": "var(--md-sys-color-on-tertiary)"
  },
  {
    "name": "Schemes/On Tertiary Container",
    "value": "var(--md-sys-color-on-tertiary-container)"
  },
  {
    "name": "Schemes/On Tertiary Fixed",
    "value": "var(--md-sys-color-on-tertiary-fixed)"
  },
  {
    "name": "Schemes/On Tertiary Fixed Variant",
    "value": "var(--md-sys-color-on-tertiary-fixed-variant)"
  },
  {
    "name": "Schemes/Outline",
    "value": "var(--md-sys-color-outline)"
  },
  {
    "name": "Schemes/Outline Variant",
    "value": "var(--md-sys-color-outline-variant)"
  },
  {
    "name": "Schemes/Primary",
    "value": "var(--md-sys-color-primary)"
  },
  {
    "name": "Schemes/Primary Container",
    "value": "var(--md-sys-color-primary-container)"
  },
  {
    "name": "Schemes/Primary Fixed",
    "value": "var(--md-sys-color-primary-fixed)"
  },
  {
    "name": "Schemes/Primary Fixed Dim",
    "value": "var(--md-sys-color-primary-fixed-dim)"
  },
  {
    "name": "Schemes/Scrim",
    "value": "var(--md-sys-color-scrim)"
  },
  {
    "name": "Schemes/Secondary",
    "value": "var(--md-sys-color-secondary)"
  },
  {
    "name": "Schemes/Secondary Container",
    "value": "var(--md-sys-color-secondary-container)"
  },
  {
    "name": "Schemes/Secondary Fixed",
    "value": "var(--md-sys-color-secondary-fixed)"
  },
  {
    "name": "Schemes/Secondary Fixed Dim",
    "value": "var(--md-sys-color-secondary-fixed-dim)"
  },
  {
    "name": "Schemes/Shadow",
    "value": "var(--md-sys-color-shadow)"
  },
  {
    "name": "Schemes/Surface",
    "value": "var(--md-sys-color-surface)"
  },
  {
    "name": "Schemes/Surface Bright",
    "value": "var(--md-sys-color-surface-bright)"
  },
  {
    "name": "Schemes/Surface Container",
    "value": "var(--md-sys-color-surface-container)"
  },
  {
    "name": "Schemes/Surface Container High",
    "value": "var(--md-sys-color-surface-container-high)"
  },
  {
    "name": "Schemes/Surface Container Highest",
    "value": "var(--md-sys-color-surface-container-highest)"
  }
];

const byName = new Map();
for (const v of await figma.variables.getLocalVariablesAsync()) {
  byName.set(v.name, v);
}

const unstamped = [];
const skipped = [];
const missing = [];
const mutatedVariableIds = [];

for (const target of TARGETS) {
  const v = byName.get(target.name);
  if (!v) {
    missing.push(target.name);
    continue;
  }
  const current = v.codeSyntax ? v.codeSyntax["WEB"] : undefined;
  if (current !== target.value) {
    skipped.push(target.name);
    continue;
  }
  v.removeVariableCodeSyntax("WEB");
  unstamped.push(target.name);
  mutatedVariableIds.push(v.id);
}

return { unstamped, skipped, missing, mutatedVariableIds };
