// AUTO-GENERATED by src/tokens/stamp.mjs from profiles/m3-kit/tokens.json — DO NOT EDIT BY HAND.
// Regenerate: node src/tokens/stamp.mjs --profile m3-kit --out profiles/m3-kit/stamp/
//
// Static (chunk 1/2) — stamps 40 Figma variable(s)' codeSyntax.WEB
// with the canonical --md-sys-* custom property (evidence #6, the proven
// Tailwind-leg mechanism: get_design_context then emits var(--md-sys-*,<fallback>)
// in generated layout code for every stamped role).
//
// PORTABLE BY NAME (evidence #5): locates each variable via
// figma.variables.getLocalVariablesAsync() + a name match — never a baked-in
// variable id, which re-mints across file copies. Run this SAME script
// unmodified against the canonical copy, a throwaway Copy, or ADS.
//
// IDEMPOTENT: a variable whose codeSyntax.WEB already equals the intended
// value is skipped, not re-stamped.
//
// ⚑ HUMAN: applying this script to a real file is a per-file authorization —
// see profiles/m3-kit/stamp/README.md before running this via use_figma.

const TARGETS = [
  {
    "name": "Static/Body Large/Line Height",
    "value": "var(--md-sys-typescale-body-large-line-height)"
  },
  {
    "name": "Static/Body Large/Size",
    "value": "var(--md-sys-typescale-body-large-font-size)"
  },
  {
    "name": "Static/Body Large/Tracking",
    "value": "var(--md-sys-typescale-body-large-tracking)"
  },
  {
    "name": "Static/Body Large/Weight",
    "value": "var(--md-sys-typescale-body-large-font-weight)"
  },
  {
    "name": "Static/Body Large/Weight-emphasized",
    "value": "var(--md-sys-typescale-emphasized-body-large-font-weight)"
  },
  {
    "name": "Static/Body Medium/Line Height",
    "value": "var(--md-sys-typescale-body-medium-line-height)"
  },
  {
    "name": "Static/Body Medium/Size",
    "value": "var(--md-sys-typescale-body-medium-font-size)"
  },
  {
    "name": "Static/Body Medium/Tracking",
    "value": "var(--md-sys-typescale-body-medium-tracking)"
  },
  {
    "name": "Static/Body Medium/Weight",
    "value": "var(--md-sys-typescale-body-medium-font-weight)"
  },
  {
    "name": "Static/Body Medium/Weight-emphasized",
    "value": "var(--md-sys-typescale-emphasized-body-medium-font-weight)"
  },
  {
    "name": "Static/Body Small/Line Height",
    "value": "var(--md-sys-typescale-body-small-line-height)"
  },
  {
    "name": "Static/Body Small/Size",
    "value": "var(--md-sys-typescale-body-small-font-size)"
  },
  {
    "name": "Static/Body Small/Tracking",
    "value": "var(--md-sys-typescale-body-small-tracking)"
  },
  {
    "name": "Static/Body Small/Weight",
    "value": "var(--md-sys-typescale-body-small-font-weight)"
  },
  {
    "name": "Static/Body Small/Weight-emphasized",
    "value": "var(--md-sys-typescale-emphasized-body-small-font-weight)"
  },
  {
    "name": "Static/Display Large/Line Height",
    "value": "var(--md-sys-typescale-display-large-line-height)"
  },
  {
    "name": "Static/Display Large/Size",
    "value": "var(--md-sys-typescale-display-large-font-size)"
  },
  {
    "name": "Static/Display Large/Tracking",
    "value": "var(--md-sys-typescale-display-large-tracking)"
  },
  {
    "name": "Static/Display Large/Weight",
    "value": "var(--md-sys-typescale-display-large-font-weight)"
  },
  {
    "name": "Static/Display Large/Weight-emphasized",
    "value": "var(--md-sys-typescale-emphasized-display-large-font-weight)"
  },
  {
    "name": "Static/Display Medium/Line Height",
    "value": "var(--md-sys-typescale-display-medium-line-height)"
  },
  {
    "name": "Static/Display Medium/Size",
    "value": "var(--md-sys-typescale-display-medium-font-size)"
  },
  {
    "name": "Static/Display Medium/Tracking",
    "value": "var(--md-sys-typescale-display-medium-tracking)"
  },
  {
    "name": "Static/Display Medium/Weight",
    "value": "var(--md-sys-typescale-display-medium-font-weight)"
  },
  {
    "name": "Static/Display Medium/Weight-emphasized",
    "value": "var(--md-sys-typescale-emphasized-display-medium-font-weight)"
  },
  {
    "name": "Static/Display Small/Line Height",
    "value": "var(--md-sys-typescale-display-small-line-height)"
  },
  {
    "name": "Static/Display Small/Size",
    "value": "var(--md-sys-typescale-display-small-font-size)"
  },
  {
    "name": "Static/Display Small/Tracking",
    "value": "var(--md-sys-typescale-display-small-tracking)"
  },
  {
    "name": "Static/Display Small/Weight",
    "value": "var(--md-sys-typescale-display-small-font-weight)"
  },
  {
    "name": "Static/Display Small/Weight-emphasized",
    "value": "var(--md-sys-typescale-emphasized-display-small-font-weight)"
  },
  {
    "name": "Static/Headline Large/Line Height",
    "value": "var(--md-sys-typescale-headline-large-line-height)"
  },
  {
    "name": "Static/Headline Large/Size",
    "value": "var(--md-sys-typescale-headline-large-font-size)"
  },
  {
    "name": "Static/Headline Large/Tracking",
    "value": "var(--md-sys-typescale-headline-large-tracking)"
  },
  {
    "name": "Static/Headline Large/Weight",
    "value": "var(--md-sys-typescale-headline-large-font-weight)"
  },
  {
    "name": "Static/Headline Large/Weight-emphasized",
    "value": "var(--md-sys-typescale-emphasized-headline-large-font-weight)"
  },
  {
    "name": "Static/Headline Medium/Line Height",
    "value": "var(--md-sys-typescale-headline-medium-line-height)"
  },
  {
    "name": "Static/Headline Medium/Size",
    "value": "var(--md-sys-typescale-headline-medium-font-size)"
  },
  {
    "name": "Static/Headline Medium/Tracking",
    "value": "var(--md-sys-typescale-headline-medium-tracking)"
  },
  {
    "name": "Static/Headline Medium/Weight",
    "value": "var(--md-sys-typescale-headline-medium-font-weight)"
  },
  {
    "name": "Static/Headline Medium/Weight-emphasized",
    "value": "var(--md-sys-typescale-emphasized-headline-medium-font-weight)"
  }
];

const byName = new Map();
for (const v of await figma.variables.getLocalVariablesAsync()) {
  byName.set(v.name, v);
}

const stamped = [];
const skipped = [];
const missing = [];
const mutatedVariableIds = [];

for (const target of TARGETS) {
  const v = byName.get(target.name);
  if (!v) {
    missing.push(target.name);
    continue;
  }
  const current = v.codeSyntax ? v.codeSyntax["WEB"] : undefined;
  if (current === target.value) {
    skipped.push(target.name);
    continue;
  }
  v.setVariableCodeSyntax("WEB", target.value);
  stamped.push(target.name);
  mutatedVariableIds.push(v.id);
}

return { stamped, skipped, missing, mutatedVariableIds };
