module NoRedundantAttributeEscapeTest exposing (all)

import Cem.Facts as Facts exposing (Facet(..))
import NoRedundantAttributeEscape exposing (rule)
import Review.Rule exposing (Rule)
import Review.Test
import Test exposing (Test, describe, test)


{-| A slice of two libraries' facts: a brand component plus a typed-HTML tag.
Every `Fact` field is written explicitly so a new field breaks this file loudly.

The rule reads `.module_` ONLY, to derive the namespaces (hence which
`*.Unsafe.Attributes` modules are escapes, and which `*.Attributes` / `*.Aria` /
`*.Events` modules to harvest). `attrRewrites` / `enums` are deliberately NOT a
setter source — they name per-component setters with CLOSED rows, which are
unsound to suggest without knowing the element. `M3e.Button` here carries a
`variant` setter precisely so the test below can prove it is NOT suggested.

-}
coveredFacts : List Facts.Fact
coveredFacts =
    [ { component = "button"
      , module_ = "M3e.Button"
      , enums = [ ( "variant", [ "filled", "outlined" ] ) ]
      , requiredSlots = []
      , multiSlots = []
      , attrRewrites = [ ( "variant", "variant" ) ]
      , slotRewrites = []
      , slotKinds = []
      , slotUpgrades = []
      , groupConstructors = []
      , facets = [ Standard, Build ]
      , requiredAttrs = []
      , actionMap = []
      , usesAction = False
      }
    , { component = "a"
      , module_ = "TypedHtml.A"
      , enums = []
      , requiredSlots = []
      , multiSlots = []
      , attrRewrites = [ ( "href", "href" ) ]
      , slotRewrites = []
      , slotKinds = []
      , slotUpgrades = []
      , groupConstructors = []
      , facets = [ Standard, Build ]
      , requiredAttrs = []
      , actionMap = []
      , usesAction = False
      }
    ]


config : Rule
config =
    rule { setterModules = [], globalAttributes = [] } coveredFacts


{-| The same rule, but told the element-independent vocabulary explicitly — the
shape a brand generated by a current `elm-cem` supplies via
`<Brand>.Review.Facts.globalAttributes`.

`dir` is present, so it must still be reported. `content` is absent (it is a
`<meta>` attribute, not a global), so it must stay silent even though a typed
`content` setter exists — the generated roster must gate exactly as the built-in
fallback does.

-}
configWithGeneratedGlobals : Rule
configWithGeneratedGlobals =
    rule
        { setterModules = []
        , globalAttributes = [ "class", "dir", "hidden", "id", "inert", "style" ]
        }
        coveredFacts



-- SETTER-MODULE EVIDENCE
--
-- The rule only suggests a setter it has SEEN declared, so every test that
-- expects an error ships the setter module that proves it. Bodies are
-- irrelevant (elm-review parses, it does not compile); the SIGNATURES are not —
-- `inert : Bool -> …` is what makes the boolean autofix safe.


typedHtmlAttributes : String
typedHtmlAttributes =
    """module TypedHtml.Attributes exposing (class, content, dir, inert, size, src, style, type_)

dir : Value -> Attr
dir value =
    value


inert : Bool -> Attr
inert flag =
    flag


class : String -> Attr
class value =
    value


style : String -> Attr
style value =
    value


type_ : Value -> Attr
type_ value =
    value


content : String -> Attr
content value =
    value


src : String -> Attr
src value =
    value


size : String -> Attr
size value =
    value
"""


typedHtmlAria : String
typedHtmlAria =
    """module TypedHtml.Aria exposing (label)

label : String -> Attr
label value =
    value
"""


brandEvents : String
brandEvents =
    """module M3e.Events exposing (onChange, onChangeWith)

onChange : msg -> Attr
onChange msg =
    msg


onChangeWith : Decoder -> Attr
onChangeWith decoder =
    decoder
"""


{-| A setter module that is NOT exposed: `hidden` is declared but kept internal,
so it is no evidence at all.
-}
brandAttributes : String
brandAttributes =
    """module M3e.Attributes exposing (variantFilled)

variantFilled : Attr
variantFilled =
    hidden True


hidden : Bool -> Attr
hidden flag =
    flag
"""


all : Test
all =
    describe "NoRedundantAttributeEscape"
        [ describe "positive (flagged)" positives
        , describe "negative (not flagged)" negatives
        , describe "false-positive bait" bait
        , describe "autofix" fixes
        ]



-- 1. POSITIVE


positives : List Test
positives =
    [ test "fromHtmlAttribute of `Html.Attributes.attribute \"dir\"` — the typed `dir` setter exists" <|
        \() ->
            [ typedHtmlAttributes
            , """module Feature exposing (view)

import Html.Attributes
import M3e.Unsafe.Attributes as Unsafe


view =
    Unsafe.fromHtmlAttribute (Html.Attributes.attribute "dir" "rtl")
"""
            ]
                |> Review.Test.runOnModules config
                |> Review.Test.expectErrorsForModules
                    [ ( "Feature"
                      , [ Review.Test.error
                            { message = attributeMessage fromHtmlAttribute "dir" "TypedHtml.Attributes.dir"
                            , details = expectedDetails fromHtmlAttribute "dir" "TypedHtml.Attributes.dir" False
                            , under = "Unsafe.fromHtmlAttribute"
                            }
                        ]
                      )
                    ]
    , test "fromHtmlAttribute of `Html.Events.on \"change\"` — the `onChangeWith` setter has exactly that shape" <|
        \() ->
            [ brandEvents
            , """module Feature exposing (view)

import Html.Events
import M3e.Unsafe.Attributes as Unsafe


view decoder =
    Unsafe.fromHtmlAttribute (Html.Events.on "change" decoder)
"""
            ]
                |> Review.Test.runOnModules config
                |> Review.Test.expectErrorsForModules
                    [ ( "Feature"
                      , [ Review.Test.error
                            { message = eventMessage fromHtmlAttribute "change" "M3e.Events.onChangeWith"
                            , details = expectedDetails fromHtmlAttribute "change" "M3e.Events.onChangeWith" False
                            , under = "Unsafe.fromHtmlAttribute"
                            }
                        ]
                      )
                    ]
    , test "a generator-supplied globalAttributes roster gates exactly as the fallback does" <|
        \() ->
            [ typedHtmlAttributes
            , """module Feature exposing (view)

import M3e.Unsafe.Attributes as Unsafe


view =
    Unsafe.customAttribute "dir" "rtl"
"""
            ]
                |> Review.Test.runOnModules configWithGeneratedGlobals
                |> Review.Test.expectErrorsForModules
                    [ ( "Feature"
                      , [ Review.Test.error
                            { message = attributeMessage customAttribute "dir" "TypedHtml.Attributes.dir"
                            , details = expectedDetails customAttribute "dir" "TypedHtml.Attributes.dir" False
                            , under = "Unsafe.customAttribute"
                            }
                        ]
                      )
                    ]
    , test "a name absent from the supplied roster stays silent even though a typed setter exists" <|
        \() ->
            [ typedHtmlAttributes
            , """module Feature exposing (view)

import M3e.Unsafe.Attributes as Unsafe


view =
    Unsafe.customAttribute "content" "<p>raw</p>"
"""
            ]
                |> Review.Test.runOnModules configWithGeneratedGlobals
                |> Review.Test.expectNoErrors
    , test "customAttribute \"inert\" — the typed `inert` setter exists" <|
        \() ->
            [ typedHtmlAttributes
            , """module Feature exposing (view)

import M3e.Unsafe.Attributes as Unsafe


view =
    Unsafe.customAttribute "inert" ""
"""
            ]
                |> Review.Test.runOnModules config
                |> Review.Test.expectErrorsForModules
                    [ ( "Feature"
                      , [ Review.Test.error
                            { message = attributeMessage customAttribute "inert" "TypedHtml.Attributes.inert"
                            , details = expectedDetails customAttribute "inert" "TypedHtml.Attributes.inert" True
                            , under = "Unsafe.customAttribute"
                            }
                            |> Review.Test.whenFixed """module Feature exposing (view)

import M3e.Unsafe.Attributes as Unsafe
import TypedHtml.Attributes


view =
    TypedHtml.Attributes.inert True
"""
                        ]
                      )
                    ]
    , test "a name-identical raw setter is flagged: `fromHtmlAttribute (Html.Attributes.class …)`" <|
        \() ->
            [ typedHtmlAttributes
            , """module Feature exposing (view)

import Html.Attributes
import M3e.Unsafe.Attributes as Unsafe


view =
    Unsafe.fromHtmlAttribute (Html.Attributes.class "row")
"""
            ]
                |> Review.Test.runOnModules config
                |> Review.Test.expectErrorsForModules
                    [ ( "Feature"
                      , [ Review.Test.error
                            { message = attributeMessage fromHtmlAttribute "class" "TypedHtml.Attributes.class"
                            , details = expectedDetails fromHtmlAttribute "class" "TypedHtml.Attributes.class" False
                            , under = "Unsafe.fromHtmlAttribute"
                            }
                        ]
                      )
                    ]
    , test "an `aria-*` name resolves against an `*.Aria` module with the prefix stripped" <|
        \() ->
            [ typedHtmlAria
            , """module Feature exposing (view)

import M3e.Unsafe.Attributes as Unsafe


view =
    Unsafe.customAttribute "aria-label" "Close"
"""
            ]
                |> Review.Test.runOnModules config
                |> Review.Test.expectErrorsForModules
                    [ ( "Feature"
                      , [ Review.Test.error
                            { message = attributeMessage customAttribute "aria-label" "TypedHtml.Aria.label"
                            , details = expectedDetails customAttribute "aria-label" "TypedHtml.Aria.label" False
                            , under = "Unsafe.customAttribute"
                            }
                        ]
                      )
                    ]
    , test "pipe form is flagged: `Html.Attributes.attribute … |> Unsafe.fromHtmlAttribute`" <|
        \() ->
            [ typedHtmlAttributes
            , """module Feature exposing (view)

import Html.Attributes
import M3e.Unsafe.Attributes as Unsafe


view =
    Html.Attributes.attribute "dir" "rtl" |> Unsafe.fromHtmlAttribute
"""
            ]
                |> Review.Test.runOnModules config
                |> Review.Test.expectErrorsForModules
                    [ ( "Feature"
                      , [ Review.Test.error
                            { message = attributeMessage fromHtmlAttribute "dir" "TypedHtml.Attributes.dir"
                            , details = expectedDetails fromHtmlAttribute "dir" "TypedHtml.Attributes.dir" False
                            , under = "Unsafe.fromHtmlAttribute"
                            }
                        ]
                      )
                    ]
    ]



-- 2. NEGATIVE


negatives : List Test
negatives =
    [ test "the fixed forms are all clean" <|
        \() ->
            [ typedHtmlAttributes
            , typedHtmlAria
            , brandEvents
            , """module Feature exposing (view)

import M3e.Events
import TypedHtml.Aria
import TypedHtml.Attributes
import TypedHtml.Values


view decoder =
    [ TypedHtml.Attributes.dir TypedHtml.Values.rtl
    , TypedHtml.Attributes.inert True
    , TypedHtml.Aria.label "Close"
    , M3e.Events.onChangeWith decoder
    ]
"""
            ]
                |> Review.Test.runOnModules config
                |> Review.Test.expectNoErrors
    , test "REGRESSION: a custom element's own attribute is NOT matched against HTML's" <|
        \() ->
            -- The reported false positive. `content` on `<raw-html>` carries the
            -- HTML string to inject; `TypedHtml.Attributes.content` is
            -- `<meta content="…">`. A custom element's attribute namespace is
            -- disjoint from HTML's, so no suggestion may be made.
            [ typedHtmlAttributes
            , """module Doc exposing (view)

import M3e.Unsafe
import M3e.Unsafe.Attributes
import TypedHtml.Attributes as TA


view html =
    M3e.Unsafe.customElement "raw-html"
        [ M3e.Unsafe.Attributes.customAttribute "content" html
        , TA.class "max-w-full py-2"
        ]
        []
"""
            ]
                |> Review.Test.runOnModules config
                |> Review.Test.expectNoErrors
    , test "the same disjointness holds away from the call site (a helper-built attribute list)" <|
        \() ->
            -- The gate is on the NAME, not on the syntactic nesting, so lifting
            -- the attribute into a helper cannot resurrect the false positive.
            [ typedHtmlAttributes
            , """module Doc exposing (rawHtmlAttrs)

import M3e.Unsafe.Attributes


rawHtmlAttrs html =
    [ M3e.Unsafe.Attributes.customAttribute "content" html ]
"""
            ]
                |> Review.Test.runOnModules config
                |> Review.Test.expectNoErrors
    , test "`src` on a custom element is dropped too — sound, though it costs a true positive" <|
        \() ->
            -- `src` on `<model-viewer>` does mean what HTML means, but from the
            -- escape site that is indistinguishable from a custom element that
            -- gives `src` its own meaning. Silence is the safe answer.
            [ typedHtmlAttributes
            , """module Feature exposing (view)

import M3e.Unsafe
import M3e.Unsafe.Attributes as Unsafe


view url =
    M3e.Unsafe.customElement "model-viewer"
        [ Unsafe.customAttribute "src" url ]
        []
"""
            ]
                |> Review.Test.runOnModules config
                |> Review.Test.expectNoErrors
    , test "an element-specific HTML attribute is not suggested: `type` (an `<input>`/`<button>` attribute)" <|
        \() ->
            [ typedHtmlAttributes
            , """module Feature exposing (view)

import M3e.Unsafe.Attributes as Unsafe


view =
    Unsafe.customAttribute "type" "button"
"""
            ]
                |> Review.Test.runOnModules config
                |> Review.Test.expectNoErrors
    , test "a BRAND per-component setter is not suggested either (closed row, unknown element)" <|
        \() ->
            [ brandAttributes
            , """module Feature exposing (view)

import M3e.Unsafe.Attributes as Unsafe


view =
    Unsafe.customAttribute "variant" "filled"
"""
            ]
                |> Review.Test.runOnModules config
                |> Review.Test.expectNoErrors
    , test "a genuinely custom attribute is legitimate: no setter of that name exists" <|
        \() ->
            [ typedHtmlAttributes
            , """module Feature exposing (view)

import M3e.Unsafe.Attributes as Unsafe


view =
    Unsafe.customAttribute "active-index" "2"
"""
            ]
                |> Review.Test.runOnModules config
                |> Review.Test.expectNoErrors
    , test "`Html.Events.stopPropagationOn` is left alone (no typed setter replicates it)" <|
        \() ->
            [ brandEvents
            , """module Feature exposing (view)

import Html.Events
import M3e.Unsafe.Attributes as Unsafe


view decoder =
    Unsafe.fromHtmlAttribute (Html.Events.stopPropagationOn "change" decoder)
"""
            ]
                |> Review.Test.runOnModules config
                |> Review.Test.expectNoErrors
    , test "`Html.Attributes.property` is left alone (IDL names are a different vocabulary)" <|
        \() ->
            [ typedHtmlAttributes
            , """module Feature exposing (view)

import Html.Attributes
import M3e.Unsafe.Attributes as Unsafe


view =
    Unsafe.fromHtmlAttribute (Html.Attributes.property "class" encoded)
"""
            ]
                |> Review.Test.runOnModules config
                |> Review.Test.expectNoErrors
    , test "an UNEXPOSED declaration in a setter module is not evidence" <|
        \() ->
            [ brandAttributes
            , """module Feature exposing (view)

import M3e.Unsafe.Attributes as Unsafe


view =
    Unsafe.customAttribute "hidden" ""
"""
            ]
                |> Review.Test.runOnModules config
                |> Review.Test.expectNoErrors
    , test "an escape on a module that is not `*.Unsafe.Attributes` is not this rule's business" <|
        \() ->
            [ typedHtmlAttributes
            , """module Feature exposing (view)

import Kit


view =
    Kit.customAttribute "inert" ""
"""
            ]
                |> Review.Test.runOnModules config
                |> Review.Test.expectNoErrors
    ]



-- 3. FALSE-POSITIVE BAIT


bait : List Test
bait =
    [ test "silent on a DYNAMIC attribute name" <|
        \() ->
            [ typedHtmlAttributes
            , """module Feature exposing (view)

import M3e.Unsafe.Attributes as Unsafe


view name value =
    Unsafe.customAttribute name value
"""
            ]
                |> Review.Test.runOnModules config
                |> Review.Test.expectNoErrors
    , test "silent on a POINT-FREE escape (no argument to inspect)" <|
        \() ->
            [ typedHtmlAttributes
            , """module Feature exposing (view)

import M3e.Unsafe.Attributes as Unsafe


view attrs =
    List.map Unsafe.fromHtmlAttribute attrs
"""
            ]
                |> Review.Test.runOnModules config
                |> Review.Test.expectNoErrors
    , test "silent on an attribute produced by a HELPER (unresolvable)" <|
        \() ->
            [ typedHtmlAttributes
            , """module Feature exposing (view)

import M3e.Unsafe.Attributes as Unsafe


view =
    Unsafe.fromHtmlAttribute (rtlAttribute "dir")
"""
            ]
                |> Review.Test.runOnModules config
                |> Review.Test.expectNoErrors
    , test "silent when the setter module is NOT part of the project (no evidence, no claim)" <|
        \() ->
            [ """module Feature exposing (view)

import M3e.Unsafe.Attributes as Unsafe


view =
    Unsafe.customAttribute "inert" ""
"""
            ]
                |> Review.Test.runOnModules config
                |> Review.Test.expectNoErrors
    ]



-- 4. AUTOFIX


fixes : List Test
fixes =
    [ test "the fix uses the module's existing ALIAS instead of re-importing" <|
        \() ->
            [ typedHtmlAttributes
            , """module Feature exposing (view)

import M3e.Unsafe.Attributes as Unsafe
import TypedHtml.Attributes as Attr


view =
    Unsafe.customAttribute "inert" ""
"""
            ]
                |> Review.Test.runOnModules config
                |> Review.Test.expectErrorsForModules
                    [ ( "Feature"
                      , [ Review.Test.error
                            { message = attributeMessage customAttribute "inert" "TypedHtml.Attributes.inert"
                            , details = expectedDetails customAttribute "inert" "TypedHtml.Attributes.inert" True
                            , under = "Unsafe.customAttribute"
                            }
                            |> Review.Test.whenFixed """module Feature exposing (view)

import M3e.Unsafe.Attributes as Unsafe
import TypedHtml.Attributes as Attr


view =
    Attr.inert True
"""
                        ]
                      )
                    ]
    , test "the `Html.Attributes.attribute` spelling of the same bare boolean is fixed too" <|
        \() ->
            [ typedHtmlAttributes
            , """module Feature exposing (view)

import Html.Attributes
import M3e.Unsafe.Attributes as Unsafe
import TypedHtml.Attributes


view =
    Unsafe.fromHtmlAttribute (Html.Attributes.attribute "inert" "")
"""
            ]
                |> Review.Test.runOnModules config
                |> Review.Test.expectErrorsForModules
                    [ ( "Feature"
                      , [ Review.Test.error
                            { message = attributeMessage fromHtmlAttribute "inert" "TypedHtml.Attributes.inert"
                            , details = expectedDetails fromHtmlAttribute "inert" "TypedHtml.Attributes.inert" True
                            , under = "Unsafe.fromHtmlAttribute"
                            }
                            |> Review.Test.whenFixed """module Feature exposing (view)

import Html.Attributes
import M3e.Unsafe.Attributes as Unsafe
import TypedHtml.Attributes


view =
    TypedHtml.Attributes.inert True
"""
                        ]
                      )
                    ]
    , test "the fix is idempotent — re-running on the fixed source finds nothing" <|
        \() ->
            [ typedHtmlAttributes
            , """module Feature exposing (view)

import M3e.Unsafe.Attributes as Unsafe
import TypedHtml.Attributes


view =
    TypedHtml.Attributes.inert True
"""
            ]
                |> Review.Test.runOnModules config
                |> Review.Test.expectNoErrors
    , test "no autofix when the setter is not a `Bool` setter (the value must be translated)" <|
        \() ->
            [ typedHtmlAttributes
            , """module Feature exposing (view)

import M3e.Unsafe.Attributes as Unsafe


view =
    Unsafe.customAttribute "dir" "rtl"
"""
            ]
                |> Review.Test.runOnModules config
                |> Review.Test.expectErrorsForModules
                    [ ( "Feature"
                      , [ Review.Test.error
                            { message = attributeMessage customAttribute "dir" "TypedHtml.Attributes.dir"
                            , details = expectedDetails customAttribute "dir" "TypedHtml.Attributes.dir" False
                            , under = "Unsafe.customAttribute"
                            }
                        ]
                      )
                    ]
    , test "no autofix for `\"true\"` — the typed Bool setter renders `inert=\"\"`, not byte-identical" <|
        \() ->
            [ typedHtmlAttributes
            , """module Feature exposing (view)

import M3e.Unsafe.Attributes as Unsafe


view =
    Unsafe.customAttribute "inert" "true"
"""
            ]
                |> Review.Test.runOnModules config
                |> Review.Test.expectErrorsForModules
                    [ ( "Feature"
                      , [ Review.Test.error
                            { message = attributeMessage customAttribute "inert" "TypedHtml.Attributes.inert"
                            , details = expectedDetails customAttribute "inert" "TypedHtml.Attributes.inert" False
                            , under = "Unsafe.customAttribute"
                            }
                        ]
                      )
                    ]
    ]



-- EXPECTED MESSAGES (mirrors of the rule's, so a wording change breaks loudly)


fromHtmlAttribute : String
fromHtmlAttribute =
    "M3e.Unsafe.Attributes.fromHtmlAttribute"


customAttribute : String
customAttribute =
    "M3e.Unsafe.Attributes.customAttribute"


attributeMessage : String -> String -> String -> String
attributeMessage escape subject setter =
    "Redundant escape: `" ++ escape ++ "` writes the `" ++ subject ++ "` attribute, which `" ++ setter ++ "` already provides"


eventMessage : String -> String -> String -> String
eventMessage escape subject setter =
    "Redundant escape: `" ++ escape ++ "` wires the `" ++ subject ++ "` event, which `" ++ setter ++ "` already provides"


expectedDetails : String -> String -> String -> Bool -> List String
expectedDetails escape subject setter fixable =
    [ "`"
        ++ escape
        ++ "` produces an `Attr` with a FREE capability row, so the compiler no longer checks which elements admit `"
        ++ subject
        ++ "`. `"
        ++ setter
        ++ "` is the typed setter for it: it carries the capability the element's closed row must list, so a misplaced attribute is a compile error instead of a silent no-op."
    , "Use `"
        ++ setter
        ++ "` and reserve `"
        ++ escape
        ++ "` for what the typed layer genuinely cannot express — a custom-element attribute with no generated setter."
    ]
        ++ (if fixable then
                []

            else
                [ "No autofix here: the escape's value has to be translated into `" ++ setter ++ "`'s argument (a value token, a decoder, or a different arity), which is a human decision." ]
           )
