// tools/check-gate-all-step-membership.test.mjs — regression guard: the
// scheduler refactor (2026-08-19 gate-all parallelization) must change WHEN
// and HOW steps run, never WHICH steps run. `gate-all-expected-steps.json`
// is a committed baseline (not self-generated by the code under test — a
// self-generated baseline can't catch a step silently dropping).
import assert from "node:assert/strict";
import fs from "node:fs";
import path from "node:path";
import { test } from "node:test";
import { execFileSync } from "node:child_process";
import { fileURLToPath } from "node:url";

const repoRoot = path.dirname(fileURLToPath(import.meta.url));
const expectedPath = path.join(repoRoot, "gate-all-expected-steps.json");

test("gate-all's step membership is unchanged after the scheduler refactor", () => {
    const expected = JSON.parse(fs.readFileSync(expectedPath, "utf8"));
    const actualRaw = execFileSync(process.execPath, [path.join(repoRoot, "gate-all.mjs"), "--list-steps-only"], {
        encoding: "utf8",
    });
    const actual = JSON.parse(actualRaw);
    assert.deepEqual(
        [...actual].sort(),
        [...expected].sort(),
        "step name set changed — a step was added, dropped, or renamed. If this is an intentional " +
            "change (e.g. a new tools/*.test.mjs file was added, changing that step's file count), " +
            "regenerate gate-all-expected-steps.json from `node tools/gate-all.mjs --list-steps-only`.",
    );
});
