#!/usr/bin/env node
// friction-review.mjs — read the friction ledger, dedup, bucket, print a digest,
// and (with --submit --yes) file ONE consolidated GitHub issue for ALL frictions.
//
//   node friction-review.mjs                 # print digest only
//   node friction-review.mjs --submit        # print digest + the exact issue body; DOES NOT file (gate)
//   node friction-review.mjs --submit --yes  # file the single consolidated issue via gh
//
// One consolidated issue (not one-per-friction) on purpose: the person tackling
// them gets the fuller context of why they were all raised together, even when
// unrelated. Buckets by the docHadIt/skillInstalled signal so each item is
// pre-classified as install-problem vs content-gap vs findability.
import fs from "node:fs"; import os from "node:os"; import path from "node:path";
import { execFileSync } from "node:child_process";

const LEDGER = process.env.M3E_OKF_LEDGER || path.join(os.homedir(), ".claude", "m3e-okf-friction-log.jsonl");
const REPO = process.env.M3E_OKF_ISSUE_REPO || "jackhp95/m3e-okf";
const submit = process.argv.includes("--submit");
const yes = process.argv.includes("--yes");

let rows = [];
try { rows = fs.readFileSync(LEDGER, "utf8").split("\n").filter(Boolean).map((l) => JSON.parse(l)); } catch {}
const open = rows.filter((r) => !r.issue); // not already filed
if (!open.length) { console.log("[friction-review] no open frictions in " + LEDGER); process.exit(0); }

// dedup by component+kind (keep the richest entry)
const byKey = new Map();
for (const r of open) { const k = r.component + "|" + r.kind; const p = byKey.get(k); if (!p || (JSON.stringify(r).length > JSON.stringify(p).length)) byKey.set(k, r); }
const items = [...byKey.values()];
// content-gap first: a genuinely-undocumented fact needs doc work even if the skill
// also wasn't installed. Then install/discoverability, then findability.
const bucket = (r) => r.docHadIt === false ? "content-gap" : r.skillInstalled === false ? "install/discoverability" : "findability/wording";
const buckets = { "install/discoverability": [], "content-gap": [], "findability/wording": [] };
for (const r of items) buckets[bucket(r)].push(r);

// build the consolidated issue body
let body = `Consolidated m3e-okf frictions captured by agents (${items.length} unique, from ${open.length} events).\n\n` +
  `Auto-collected via friction-log; classified by whether the fact was already documented (\`docHadIt\`) and whether the skill was installed (\`skillInstalled\`).\n`;
for (const b of Object.keys(buckets)) {
  if (!buckets[b].length) continue;
  body += `\n## ${b} (${buckets[b].length})\n`;
  for (const r of buckets[b]) body += `- **${r.component}** — ${r.kind}: ${r.note || ""}${r.resolved ? ` → correct: \`${r.resolved}\`` : ""}${r.repo ? ` _(seen in ${r.repo})_` : ""}\n`;
}
body += `\n---\nGenerated by scripts/friction-review.mjs. install/discoverability items usually mean the skill wasn't reachable, not that docs are missing.`;

console.log("=== DIGEST ===\n" + body + "\n");
if (!submit) { console.log("(run with --submit to see the issue that WOULD be filed; --submit --yes to file it)"); process.exit(0); }
const title = `m3e-okf: ${items.length} agent frictions (${Object.entries(buckets).filter(([, v]) => v.length).map(([k, v]) => `${v.length} ${k.split("/")[0]}`).join(", ")})`;
if (!yes) { console.log(`\n=== WOULD FILE (title) ===\n${title}\n\n(pass --yes to actually create the issue on ${REPO})`); process.exit(0); }
const url = execFileSync("gh", ["issue", "create", "--repo", REPO, "--title", title, "--body", body], { encoding: "utf8" }).trim();
console.log("[friction-review] filed: " + url);
// mark the events as filed
const marked = rows.map((r) => (r.issue ? r : { ...r, issue: url }));
fs.writeFileSync(LEDGER, marked.map((r) => JSON.stringify(r)).join("\n") + "\n");
console.log("[friction-review] ledger marked filed.");
