// AUTO-GENERATED by src/tokens/stamp.mjs from profiles/m3-kit/tokens.json — DO NOT EDIT BY HAND.
// Regenerate: node src/tokens/stamp.mjs --profile m3-kit --out profiles/m3-kit/stamp/
//
// INVERSE of stamp/02-corner.js.
// Corner — restores 10 Figma variable(s)' codeSyntax.WEB
// to "{}" (removeVariableCodeSyntax). The checked-in token-table dump measures
// 0/304 variables with any codeSyntax today (evidence #13) — for this table,
// "restore to {}" and "restore to the recorded pre-state" are the same
// operation. If a target file's PRE-stamp state was ever non-empty, restore
// from the 00-snapshot.json captured before stamping instead (see README.md).
//
// PORTABLE BY NAME, IDEMPOTENT: same discipline as the stamp script — locates
// by name, and skips a variable whose codeSyntax.WEB does not currently equal
// the value we would have stamped (already restored, or never ours to touch).

const TARGETS = [
  {
    "name": "Corner/Extra-extra-large",
    "value": "var(--md-sys-shape-corner-extra-extra-large)"
  },
  {
    "name": "Corner/Extra-large",
    "value": "var(--md-sys-shape-corner-extra-large)"
  },
  {
    "name": "Corner/Extra-large-increased",
    "value": "var(--md-sys-shape-corner-extra-large-increased)"
  },
  {
    "name": "Corner/Extra-small",
    "value": "var(--md-sys-shape-corner-extra-small)"
  },
  {
    "name": "Corner/Full",
    "value": "var(--md-sys-shape-corner-full)"
  },
  {
    "name": "Corner/Large",
    "value": "var(--md-sys-shape-corner-large)"
  },
  {
    "name": "Corner/Large-increased",
    "value": "var(--md-sys-shape-corner-large-increased)"
  },
  {
    "name": "Corner/Medium",
    "value": "var(--md-sys-shape-corner-medium)"
  },
  {
    "name": "Corner/None",
    "value": "var(--md-sys-shape-corner-none)"
  },
  {
    "name": "Corner/Small",
    "value": "var(--md-sys-shape-corner-small)"
  }
];

const byName = new Map();
for (const v of await figma.variables.getLocalVariablesAsync()) {
  byName.set(v.name, v);
}

const unstamped = [];
const skipped = [];
const missing = [];
const mutatedVariableIds = [];

for (const target of TARGETS) {
  const v = byName.get(target.name);
  if (!v) {
    missing.push(target.name);
    continue;
  }
  const current = v.codeSyntax ? v.codeSyntax["WEB"] : undefined;
  if (current !== target.value) {
    skipped.push(target.name);
    continue;
  }
  v.removeVariableCodeSyntax("WEB");
  unstamped.push(target.name);
  mutatedVariableIds.push(v.id);
}

return { unstamped, skipped, missing, mutatedVariableIds };
