// AUTO-GENERATED by src/tokens/stamp.mjs from profiles/m3-kit/tokens.json — DO NOT EDIT BY HAND.
// Regenerate: node src/tokens/stamp.mjs --profile m3-kit --out profiles/m3-kit/stamp/
//
// INVERSE of stamp/03-static.js.
// Static (chunk 1/2) — restores 40 Figma variable(s)' codeSyntax.WEB
// to "{}" (removeVariableCodeSyntax). The checked-in token-table dump measures
// 0/304 variables with any codeSyntax today (evidence #13) — for this table,
// "restore to {}" and "restore to the recorded pre-state" are the same
// operation. If a target file's PRE-stamp state was ever non-empty, restore
// from the 00-snapshot.json captured before stamping instead (see README.md).
//
// PORTABLE BY NAME, IDEMPOTENT: same discipline as the stamp script — locates
// by name, and skips a variable whose codeSyntax.WEB does not currently equal
// the value we would have stamped (already restored, or never ours to touch).

const TARGETS = [
  {
    "name": "Static/Body Large/Line Height",
    "value": "var(--md-sys-typescale-body-large-line-height)"
  },
  {
    "name": "Static/Body Large/Size",
    "value": "var(--md-sys-typescale-body-large-font-size)"
  },
  {
    "name": "Static/Body Large/Tracking",
    "value": "var(--md-sys-typescale-body-large-tracking)"
  },
  {
    "name": "Static/Body Large/Weight",
    "value": "var(--md-sys-typescale-body-large-font-weight)"
  },
  {
    "name": "Static/Body Large/Weight-emphasized",
    "value": "var(--md-sys-typescale-emphasized-body-large-font-weight)"
  },
  {
    "name": "Static/Body Medium/Line Height",
    "value": "var(--md-sys-typescale-body-medium-line-height)"
  },
  {
    "name": "Static/Body Medium/Size",
    "value": "var(--md-sys-typescale-body-medium-font-size)"
  },
  {
    "name": "Static/Body Medium/Tracking",
    "value": "var(--md-sys-typescale-body-medium-tracking)"
  },
  {
    "name": "Static/Body Medium/Weight",
    "value": "var(--md-sys-typescale-body-medium-font-weight)"
  },
  {
    "name": "Static/Body Medium/Weight-emphasized",
    "value": "var(--md-sys-typescale-emphasized-body-medium-font-weight)"
  },
  {
    "name": "Static/Body Small/Line Height",
    "value": "var(--md-sys-typescale-body-small-line-height)"
  },
  {
    "name": "Static/Body Small/Size",
    "value": "var(--md-sys-typescale-body-small-font-size)"
  },
  {
    "name": "Static/Body Small/Tracking",
    "value": "var(--md-sys-typescale-body-small-tracking)"
  },
  {
    "name": "Static/Body Small/Weight",
    "value": "var(--md-sys-typescale-body-small-font-weight)"
  },
  {
    "name": "Static/Body Small/Weight-emphasized",
    "value": "var(--md-sys-typescale-emphasized-body-small-font-weight)"
  },
  {
    "name": "Static/Display Large/Line Height",
    "value": "var(--md-sys-typescale-display-large-line-height)"
  },
  {
    "name": "Static/Display Large/Size",
    "value": "var(--md-sys-typescale-display-large-font-size)"
  },
  {
    "name": "Static/Display Large/Tracking",
    "value": "var(--md-sys-typescale-display-large-tracking)"
  },
  {
    "name": "Static/Display Large/Weight",
    "value": "var(--md-sys-typescale-display-large-font-weight)"
  },
  {
    "name": "Static/Display Large/Weight-emphasized",
    "value": "var(--md-sys-typescale-emphasized-display-large-font-weight)"
  },
  {
    "name": "Static/Display Medium/Line Height",
    "value": "var(--md-sys-typescale-display-medium-line-height)"
  },
  {
    "name": "Static/Display Medium/Size",
    "value": "var(--md-sys-typescale-display-medium-font-size)"
  },
  {
    "name": "Static/Display Medium/Tracking",
    "value": "var(--md-sys-typescale-display-medium-tracking)"
  },
  {
    "name": "Static/Display Medium/Weight",
    "value": "var(--md-sys-typescale-display-medium-font-weight)"
  },
  {
    "name": "Static/Display Medium/Weight-emphasized",
    "value": "var(--md-sys-typescale-emphasized-display-medium-font-weight)"
  },
  {
    "name": "Static/Display Small/Line Height",
    "value": "var(--md-sys-typescale-display-small-line-height)"
  },
  {
    "name": "Static/Display Small/Size",
    "value": "var(--md-sys-typescale-display-small-font-size)"
  },
  {
    "name": "Static/Display Small/Tracking",
    "value": "var(--md-sys-typescale-display-small-tracking)"
  },
  {
    "name": "Static/Display Small/Weight",
    "value": "var(--md-sys-typescale-display-small-font-weight)"
  },
  {
    "name": "Static/Display Small/Weight-emphasized",
    "value": "var(--md-sys-typescale-emphasized-display-small-font-weight)"
  },
  {
    "name": "Static/Headline Large/Line Height",
    "value": "var(--md-sys-typescale-headline-large-line-height)"
  },
  {
    "name": "Static/Headline Large/Size",
    "value": "var(--md-sys-typescale-headline-large-font-size)"
  },
  {
    "name": "Static/Headline Large/Tracking",
    "value": "var(--md-sys-typescale-headline-large-tracking)"
  },
  {
    "name": "Static/Headline Large/Weight",
    "value": "var(--md-sys-typescale-headline-large-font-weight)"
  },
  {
    "name": "Static/Headline Large/Weight-emphasized",
    "value": "var(--md-sys-typescale-emphasized-headline-large-font-weight)"
  },
  {
    "name": "Static/Headline Medium/Line Height",
    "value": "var(--md-sys-typescale-headline-medium-line-height)"
  },
  {
    "name": "Static/Headline Medium/Size",
    "value": "var(--md-sys-typescale-headline-medium-font-size)"
  },
  {
    "name": "Static/Headline Medium/Tracking",
    "value": "var(--md-sys-typescale-headline-medium-tracking)"
  },
  {
    "name": "Static/Headline Medium/Weight",
    "value": "var(--md-sys-typescale-headline-medium-font-weight)"
  },
  {
    "name": "Static/Headline Medium/Weight-emphasized",
    "value": "var(--md-sys-typescale-emphasized-headline-medium-font-weight)"
  }
];

const byName = new Map();
for (const v of await figma.variables.getLocalVariablesAsync()) {
  byName.set(v.name, v);
}

const unstamped = [];
const skipped = [];
const missing = [];
const mutatedVariableIds = [];

for (const target of TARGETS) {
  const v = byName.get(target.name);
  if (!v) {
    missing.push(target.name);
    continue;
  }
  const current = v.codeSyntax ? v.codeSyntax["WEB"] : undefined;
  if (current !== target.value) {
    skipped.push(target.name);
    continue;
  }
  v.removeVariableCodeSyntax("WEB");
  unstamped.push(target.name);
  mutatedVariableIds.push(v.id);
}

return { unstamped, skipped, missing, mutatedVariableIds };
