module NoProprietaryDsClasses exposing (rule)

{-|

@docs rule

-}

import Elm.Syntax.Expression as Expression exposing (Expression)
import Elm.Syntax.Node as Node exposing (Node(..))
import Review.ModuleNameLookupTable as ModuleNameLookupTable exposing (ModuleNameLookupTable)
import Review.Rule as Rule exposing (Error, Rule)


{-| Reports CSS classes that do more than LAYOUT.

The standing rule this encodes: **Tailwind is for layout only.** Positioning,
sizing, spacing, flex/grid and flow are a legitimate use of a utility class.
**Styling — colour, background, border, radius, elevation/shadow, typography —
must come from an m3e component**, never from a utility class. A page that
paints `bg-surface-container-high text-on-surface rounded-md-corner-large` has
reimplemented `m3e-card` in Tailwind: it inherits none of the component's state
layers, motion, density or accessibility, and it silently drifts from the theme
the moment a token is renamed.

It also keeps the original charter: `ds-*` / `t-*` classes are project-proprietary
tokens that are **not** part of Material and ship **no CSS** in this library, so
applying one renders nothing. The compiler cannot see either failure because
`class : String -> Attr … msg` accepts any string.

The rule inspects string-literal arguments to `class` and `classList` from
`Html.Attributes`, `TypedHtml.Attributes`, `M3e.Attributes` and `Svg.Attributes`,
plus any `…withClass` builder setter, and classifies every space-separated token.


## Classification

Each token is reduced to its base utility — variant prefixes (`md:`, `hover:`,
`[&>*]:`) and the `!`/`-` modifiers are stripped — and then sorted into one of
three buckets:

  - **Proprietary** (`ds-`, `t-`) — renders nothing. Reported.
  - **Styling** — a Tailwind family that paints: `bg-`, `border-`, `rounded-`,
    `shadow-`, `ring-`, `outline-`, `divide-`, `fill-`, `stroke-`, `font-`,
    `leading-`, `tracking-`, `list-`, the filter/blend families, the gradient
    stops, the typographic keywords (`uppercase`, `italic`, `underline`, …), and
    any `text-` that is not alignment/wrapping. Reported.
  - **Allowed** — true layout utilities (`flex`, `grid-cols-2`, `gap-4`, `w-full`,
    `p-4`, `inset-x-0`, `z-20`, `overflow-hidden`, …), the accessibility and
    interaction utilities (`sr-only`, `pointer-events-none`, `cursor-pointer`),
    the `m3e-*` token utilities generated by `tailwind-m3e-web` (these set a
    component's **own** documented custom properties, which is styling _through_
    m3e rather than around it), and any class that is not a Tailwind utility at
    all — a project semantic hook like `compose-slot-panel` or a test selector.

Unknown tokens are **allowed** deliberately. Tailwind's painting surface is
enumerable, a project's semantic hooks are not, so denying by styling family
catches the regressions that matter without flagging every new CSS/test hook.


## Known limit

The rule reads literals, not values. It descends through `++`, parentheses, and
`if`/`case` branches to find every literal in a class argument, so
`class (base ++ " bg-surface")` is caught. But a class assembled entirely out of
non-literals — a `let`-bound `String`, or a helper like
`class (densityClass model.density)` — is invisible, because knowing what those
hold needs dataflow analysis this rule does not attempt. If you are hiding a
painting class behind a function to dodge this rule, that is on you.


## Fail

    Html.div [ Attr.class "bg-surface-container-high rounded-lg" ] []

    TA.div [ TA.class "text-body-lg text-on-surface-variant" ] []

    Attr.class "ds-card-media"


## Success

    Html.div [ Attr.class "flex items-center gap-2" ] []

    TA.div [ TA.class "grid grid-cols-2 p-4 overflow-hidden" ] []

    M3e.card [ MA.class "m3e-card-padding-[0.625rem]" ] []

-}
rule : Rule
rule =
    Rule.newModuleRuleSchemaUsingContextCreator "NoProprietaryDsClasses" initialContext
        |> Rule.withExpressionEnterVisitor expressionVisitor
        |> Rule.fromModuleRuleSchema


type alias Context =
    { lookupTable : ModuleNameLookupTable }


initialContext : Rule.ContextCreator () Context
initialContext =
    Rule.initContextCreator (\lookupTable () -> { lookupTable = lookupTable })
        |> Rule.withModuleNameLookupTable


expressionVisitor : Node Expression -> Context -> ( List (Error {}), Context )
expressionVisitor node context =
    case Node.value node of
        Expression.Application (fn :: arg :: []) ->
            ( checkClassCall context fn arg, context )

        _ ->
            ( [], context )


checkClassCall : Context -> Node Expression -> Node Expression -> List (Error {})
checkClassCall context fn arg =
    case fn of
        Node _ (Expression.FunctionOrValue _ name) ->
            if isClassLike context fn name then
                checkClassArgument arg

            else if name == "classList" && resolvesToClassModule context fn then
                checkClassList arg

            else
                []

        _ ->
            []


{-| `class` from any of the class-bearing attribute modules, or any builder
setter named `withClass`.
-}
isClassLike : Context -> Node Expression -> String -> Bool
isClassLike context fn name =
    (name == "class" && resolvesToClassModule context fn)
        || (name == "withClass")


{-| The docs app reaches `class` through four different modules — `TypedHtml`'s
and `M3e`'s typed attribute modules carry the overwhelming majority of call
sites, so resolving only `Html.Attributes` would leave the rule toothless here.
-}
resolvesToClassModule : Context -> Node Expression -> Bool
resolvesToClassModule context fn =
    case ModuleNameLookupTable.moduleNameFor context.lookupTable fn of
        Just [ "Html", "Attributes" ] ->
            True

        Just [ "TypedHtml", "Attributes" ] ->
            True

        Just [ "M3e", "Attributes" ] ->
            True

        Just [ "Svg", "Attributes" ] ->
            True

        _ ->
            False


{-| A class argument is rarely just a literal. Real call sites concatenate a
computed part onto a fixed part (`class (bodyCls ++ " text-on-surface-variant")`)
or pick between literals in a branch, and checking only `Expression.Literal`
missed every one of those — a painting class hidden behind a `++` was silently
unenforced. So descend through the shapes that still contain a checkable literal.

The computed halves (a `let`-bound `String`, a function call like
`densityClass model.theme.density`) remain invisible: knowing what they hold needs
dataflow analysis this rule does not do. That is a documented limit, not an
oversight — see the module docs.

-}
checkClassArgument : Node Expression -> List (Error {})
checkClassArgument node =
    case Node.value node of
        Expression.Literal str ->
            errorsForClassString node str

        Expression.ParenthesizedExpression inner ->
            checkClassArgument inner

        Expression.OperatorApplication "++" _ left right ->
            checkClassArgument left ++ checkClassArgument right

        Expression.IfBlock _ onTrue onFalse ->
            checkClassArgument onTrue ++ checkClassArgument onFalse

        Expression.CaseExpression { cases } ->
            List.concatMap (\( _, body ) -> checkClassArgument body) cases

        _ ->
            []


{-| `classList [ ( "ds-active", cond ), … ]` — check each tuple's first element.
-}
checkClassList : Node Expression -> List (Error {})
checkClassList node =
    case Node.value node of
        Expression.ListExpr entries ->
            List.concatMap checkClassListEntry entries

        _ ->
            []


checkClassListEntry : Node Expression -> List (Error {})
checkClassListEntry node =
    case Node.value node of
        Expression.TupledExpression (keyNode :: _) ->
            checkClassArgument keyNode

        _ ->
            []



-- REPORTING -------------------------------------------------------------------


{-| At most one error per category per literal, each naming the exact tokens at
fault so the fix is mechanical from the report alone.
-}
errorsForClassString : Node Expression -> String -> List (Error {})
errorsForClassString node str =
    let
        tokens : List String
        tokens =
            String.words str

        proprietary : List String
        proprietary =
            List.filter (\token -> classify token == Proprietary) tokens

        styling : List String
        styling =
            List.filter (\token -> classify token == Styling) tokens
    in
    List.filterMap identity
        [ if List.isEmpty proprietary then
            Nothing

          else
            Just (proprietaryError node proprietary)
        , if List.isEmpty styling then
            Nothing

          else
            Just (stylingError node styling)
        ]


proprietaryError : Node Expression -> List String -> Error {}
proprietaryError node tokens =
    Rule.error
        { message = "Proprietary CSS class — not Material, ships no CSS"
        , details =
            [ "`ds-*` and `t-*` classes are project-proprietary tokens that are not part of Material and ship no CSS in this library, so they render nothing."
            , "Offending: " ++ String.join ", " tokens
            , "Use a typed M3e slot/role binding or a real utility class instead."
            ]
        }
        (Node.range node)


stylingError : Node Expression -> List String -> Error {}
stylingError node tokens =
    Rule.error
        { message = "Non-layout CSS class — styling must come from an m3e component"
        , details =
            [ "Tailwind is for LAYOUT only. Colour, background, border, radius, elevation/shadow and typography must come from an m3e component, not a utility class."
            , "Offending: " ++ String.join ", " tokens
            , "Reach for the component that already owns this surface — `m3e-card` for a panel, `m3e-list` + `m3e-list-item` for rows, `m3e-divider` for a rule, a typography component for a text role — instead of repainting it. A hand-painted surface inherits none of the component's state layers, motion, density or accessibility, and drifts from the theme the moment a token is renamed."
            , "Layout utilities (`flex`, `grid-cols-2`, `gap-4`, `w-full`, `p-4`, `z-20`, …) stay. So do the generated `m3e-*` token utilities, which set a component's own documented custom properties."
            ]
        }
        (Node.range node)



-- CLASSIFICATION --------------------------------------------------------------


type Classification
    = Proprietary
    | Styling
    | Allowed


classify : String -> Classification
classify token =
    let
        base : String
        base =
            token |> utilityPart |> stripModifiers
    in
    if base == "" then
        Allowed

    else if isProprietary base then
        Proprietary

    else if isM3eTokenUtility base then
        Allowed

    else if String.startsWith "[" base then
        classifyArbitraryProperty base

    else if isShadowedStyling base then
        Styling

    else if isLayout base then
        Allowed

    else if isStyling base then
        Styling

    else
        Allowed


{-| Keep the final `:`-separated segment — the utility itself, with every variant
prefix (`md:`, `hover:`, `group-hover:`, `[&>*]:`, `[:not([selected])]:`) gone.

Depth tracking is load-bearing: an arbitrary value legitimately contains a colon
(`[--m3e-nav-rail-icon-button-inset:auto]`, `bg-[url(https://x)]`), and splitting
naively on every `:` would shred it into a meaningless tail.

-}
utilityPart : String -> String
utilityPart token =
    token
        |> String.foldl
            (\char ( depth, current ) ->
                case char of
                    '[' ->
                        ( depth + 1, current ++ String.fromChar char )

                    '(' ->
                        ( depth + 1, current ++ String.fromChar char )

                    ']' ->
                        ( depth - 1, current ++ String.fromChar char )

                    ')' ->
                        ( depth - 1, current ++ String.fromChar char )

                    ':' ->
                        if depth == 0 then
                            ( depth, "" )

                        else
                            ( depth, current ++ String.fromChar char )

                    _ ->
                        ( depth, current ++ String.fromChar char )
            )
            ( 0, "" )
        |> Tuple.second


{-| Drop the `!` important marker and the leading `-` of a negative utility
(`-mx-4` is the same family as `mx-4`).
-}
stripModifiers : String -> String
stripModifiers utility =
    utility
        |> dropPrefix "!"
        |> dropPrefix "-"


dropPrefix : String -> String -> String
dropPrefix prefix str =
    if String.startsWith prefix str then
        String.dropLeft (String.length prefix) str

    else
        str


isProprietary : String -> Bool
isProprietary base =
    String.startsWith "ds-" base || String.startsWith "t-" base


{-| `tailwind-m3e-web` generates one `m3e-<token>-*` utility per public
`--m3e-*` custom property. These drive a component's OWN documented knobs, so
they are styling _through_ m3e rather than around it — the sanctioned bridge.
-}
isM3eTokenUtility : String -> Bool
isM3eTokenUtility base =
    String.startsWith "m3e-" base


{-| A bare arbitrary property (`[--m3e-inset:auto]`, `[color:red]`). Setting an
m3e design token is the sanctioned bridge; setting any other raw CSS property
from a class is exactly the hand-painting this rule exists to stop.
-}
classifyArbitraryProperty : String -> Classification
classifyArbitraryProperty base =
    if String.startsWith "[--m3e-" base then
        Allowed

    else
        Styling


{-| Styling families whose names begin with a LAYOUT prefix, so `isLayout` would
otherwise swallow them: `inset-shadow-lg` and `inset-ring-2` are elevation, not
the `inset-` positioning family. Checked ahead of `isLayout` for that reason.
-}
isShadowedStyling : String -> Bool
isShadowedStyling base =
    List.any (\prefix -> String.startsWith prefix base)
        [ "inset-shadow-"
        , "inset-ring-"
        ]


isLayout : String -> Bool
isLayout base =
    List.member base layoutKeywords
        || List.any (\prefix -> String.startsWith prefix base) layoutPrefixes


isStyling : String -> Bool
isStyling base =
    List.member base stylingKeywords
        || List.any (\prefix -> String.startsWith prefix base) stylingPrefixes


{-| Single-word layout utilities: display, position, and the accessibility pair.
-}
layoutKeywords : List String
layoutKeywords =
    [ "flex"
    , "grid"
    , "contents"
    , "block"
    , "inline"
    , "inline-block"
    , "inline-flex"
    , "inline-grid"
    , "inline-table"
    , "table"
    , "flow-root"
    , "list-item"
    , "hidden"
    , "static"
    , "fixed"
    , "absolute"
    , "relative"
    , "sticky"
    , "isolate"
    , "isolation-auto"
    , "visible"
    , "invisible"
    , "collapse"
    , "sr-only"
    , "not-sr-only"
    , "truncate"
    , "container"
    , "transform-none"
    , "antialiased-none"
    ]


{-| Layout utility families, matched as `prefix-`. Ordering is irrelevant because
`isStyling` is only consulted after this returns `False`, and the two lists are
disjoint by construction — the one genuine overlap, `text-`, is resolved by
listing the alignment/wrapping members explicitly here.
-}
layoutPrefixes : List String
layoutPrefixes =
    [ -- flex + grid
      "flex-"
    , "grid-"
    , "col-"
    , "row-"
    , "auto-cols-"
    , "auto-rows-"
    , "gap-"
    , "space-"
    , "items-"
    , "justify-"
    , "place-"
    , "content-"
    , "self-"
    , "order-"
    , "basis-"
    , "grow-"
    , "shrink-"
    , "columns-"

    -- sizing
    , "w-"
    , "h-"
    , "size-"
    , "min-w-"
    , "max-w-"
    , "min-h-"
    , "max-h-"
    , "aspect-"

    -- padding
    , "p-"
    , "px-"
    , "py-"
    , "pt-"
    , "pr-"
    , "pb-"
    , "pl-"
    , "ps-"
    , "pe-"

    -- margin
    , "m-"
    , "mx-"
    , "my-"
    , "mt-"
    , "mr-"
    , "mb-"
    , "ml-"
    , "ms-"
    , "me-"

    -- position + stacking
    , "inset-x-"
    , "inset-y-"
    , "inset-"
    , "top-"
    , "right-"
    , "bottom-"
    , "left-"
    , "start-"
    , "end-"
    , "z-"
    , "float-"
    , "clear-"

    -- flow + overflow
    , "overflow-"
    , "overscroll-"
    , "object-"
    , "box-"
    , "break-"
    , "whitespace-"
    , "hyphens-"
    , "wrap-"

    -- text alignment and wrapping: layout concerns that happen to live under
    -- the `text-` prefix. Every other `text-*` is colour or type scale.
    , "text-left"
    , "text-center"
    , "text-right"
    , "text-justify"
    , "text-start"
    , "text-end"
    , "text-wrap"
    , "text-nowrap"
    , "text-balance"
    , "text-pretty"
    , "text-ellipsis"
    , "text-clip"

    -- transform + motion
    , "translate-"
    , "rotate-"
    , "scale-"
    , "skew-"
    , "transform-"
    , "origin-"
    , "perspective-"
    , "transition"
    , "duration-"
    , "delay-"
    , "ease-"
    , "animate-"
    , "will-change-"

    -- interaction, scrolling, accessibility. Not paint: none of these carry a
    -- colour, a type scale, a border or an elevation.
    , "snap-"
    , "scroll-"
    , "touch-"
    , "select-"
    , "resize-"
    , "cursor-"
    , "pointer-events-"
    , "appearance-"
    , "opacity-"
    , "contain-"
    , "@container"
    ]


{-| Typographic and decorative single-word utilities.
-}
stylingKeywords : List String
stylingKeywords =
    [ "italic"
    , "not-italic"
    , "uppercase"
    , "lowercase"
    , "capitalize"
    , "normal-case"
    , "underline"
    , "overline"
    , "line-through"
    , "no-underline"
    , "antialiased"
    , "subpixel-antialiased"
    , "ordinal"
    , "slashed-zero"
    , "lining-nums"
    , "oldstyle-nums"
    , "proportional-nums"
    , "tabular-nums"
    , "diagonal-fractions"
    , "stacked-fractions"
    , "normal-nums"
    , "border"
    , "rounded"
    , "shadow"
    , "ring"
    , "outline"
    , "grayscale"
    , "invert"
    , "sepia"
    , "backdrop-grayscale"
    , "backdrop-invert"
    , "backdrop-sepia"
    ]


{-| The painting families. Every one of these sets a colour, a background, a
border, a radius, an elevation, a filter or a type scale.
-}
stylingPrefixes : List String
stylingPrefixes =
    [ -- background + gradients
      "bg-"
    , "from-"
    , "via-"
    , "to-"

    -- borders, outlines, rings, dividers
    , "border-"
    , "divide-"
    , "outline-"
    , "ring-"
    , "rounded-"

    -- elevation
    , "shadow-"
    , "drop-shadow-"
    , "inset-shadow-"
    , "inset-ring-"
    , "text-shadow-"
    , "elevation-"

    -- typography
    , "font-"
    , "leading-"
    , "tracking-"
    , "decoration-"
    , "indent-"
    , "list-"
    , "align-"

    -- colour on non-text surfaces
    , "text-"
    , "fill-"
    , "stroke-"
    , "accent-"
    , "caret-"
    , "placeholder-"

    -- filters + blend
    , "blur-"
    , "brightness-"
    , "contrast-"
    , "saturate-"
    , "hue-rotate-"
    , "backdrop-"
    , "mix-blend-"
    , "bg-blend-"
    ]
